---
- name: APT module
  hosts: ubuntu1
  become: True
  remote_user: trosales
  tasks:
   - name: Actualizar lista de paquetes
     apt: update_cache=yes
   - name: Actualizar paquetes
     apt: upgrade=dist
   - name: Instalar nginx
     apt: name=nginx state=latest
...
