---
- name: assert module
  hosts: localhost
  #vars:
  #  numero: 10
  tasks:
   - include_vars: variables.yml
   - assert:
       msg: "Numero tiene que estar entre 0 y 100"
       that:
         - ansible_os_family != "RedHAt"
         - numero <= 100
         - numero > 0

   - assert:
       msg: "Numero tiene que ser mayor a 100"
       that:
         - numero > 100
         
