version: "3"
services:
  master:
    image: thomasdocker92/ansible-centos-master
    networks:
      ansible:
        ipv4_address: 192.168.10.2
  ubuntu:
    image: thomasdocker92/ansible-ubuntu-client
    networks:
      ansible:
        ipv4_address: 192.168.10.3
  debian:
    image: thomasdocker92/ansible-debian-client
    networks:
      ansible:
        ipv4_address: 192.168.10.4

networks:
  ansible:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "192.168.10.0/24"
