version: "3"
services:
  master:
    image: thomasdocker92/ansible-centos-master:latest
    networks:
      ansiblenet:
        ipv4_address: 192.168.0.1
  ubuntu:
    image: thomasdocker92/ansible-ubuntu-client
    networks:
      ansiblenet:
        ipv4_address: 192.168.0.2
  debian:
    image: thomasdocker92/ansible-debian-client
    networks:
      ansiblenet:
        ipv4_address: 192.168.0.3

networks:
  ansiblenet:
    ipam:
      driver: default
      config:
        - subnet: "192.168.0.0/24"
