---
- name: Instalar apache2
  apt: name=apache2 state=latest
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- name: Iniciar y habilitar servicio
  service: name=apache2 state=started enabled=true

- name: Copiar fichero de configuracion
  copy: src=apache2.conf dest=/etc/apache2/apache2.conf
  notify: restart_httpd

- name: Copiar ficher index.html
  template: src=index.html.j2 dest=/var/www/html/index.html
  register: copiado

- name: Mostrar contenido
  command: cat /var/www/html/index.html
  register: output
  when: copiado.changed == true

- debug: var=copiado
  when: copiado.changed == true
...
