---
- name: Actualizar configuracion sshd_config
  hosts: localhost
  connection: local
  tasks:
   - name: Copiar ficher
     copy: src=sshd_config dest=/etc/ssh/sshd_config
     notify: restart_sshd
  handlers:
   - name: restart_sshd
     service: name=sshd state=restarted
...
